Skip tests for Python 3 as hardcoded pickle binary is incompatible
I'm getting this error when unpickling with Python 3 (no stacktrace):

```
TypeError: an integer is required (got type str)
```